language: node_js
node_js: stable

sudo: required

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install

# before_script:
#   - git clone https://github.com/jerryc127/hexo-theme-butterfly.git themes/Butterfly

script:
  - hexo clean 
  - hexo g 
  - hexo douban
  - cd ./public
  - git init
  - git config user.name "${GIT_NAME}"
  - git config user.email "${GIT_EMAIL}"
  - git add .
  - git commit -m "Update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  # - git push --force --quiet "https://${CDT_TOKEN}@${CDT_REF}" master:master

# after_script:

branches:
  only:
    - hexo